defaults:
  - default.yaml

launcher:
  timeout_min: 30
  nodes: 2
  tasks_per_node: 4
  cpus_per_task: 10
  mem_gb: 300
  partition: gpu-debug
  account: mit186
  additional_parameters:
    gpus: 8
    constraint: lustre