_target_: src.models.core_module.PhaseNetTFModule

net:
  _target_: src.models.components.deeplabv3p.DeepLabV3Plus
  out_channels: 4
  image_height: 64

sgram_generator:
  _target_: src.models.spectrogram.GenSgram
  n_fft: 256
  hop_length: 1
  freqmin: 0
  freqmax: 10
  dt_s: 0.025
  height: 64
  width: 4800
  max_clamp: 3000

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 0.001
  weight_decay: 0.001
  amsgrad: False

scheduler:
  _target_: torch.optim.lr_scheduler.MultiStepLR
  _partial_: True
  milestones: [30, 60, 90, 120]
  gamma: 0.6

loss: "kl_div"
phases: ["P", "S", "PS"]
output_classes_weight: [0.25, 0.25, 0.5, 0.0]
extract_peaks_sensitive_possibility: [0.5, 0.5, 0.3]
extract_peaks_sensitive_distances_in_seconds: 5.0
window_length_in_npts: 4800
dt_s: 0.025
metrics_true_positive_threshold_s: 1.0
